#/appspec.yml
version: 0.0
os: linux
files:
  - source: /
    destination: /home/projects/build
hooks:
  BeforeInstall:
    - location: /scripts/initialize.sh
      runas: root
  AfterInstall:
    - location: /scripts/npminstall.sh

  ApplicationStart:
    - location: /scripts/start.sh
      runas: root