on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: expressme.dev
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
      - name: Start Script
        run: sh ../../install.sh -xe
        
      - name: Testing the console
        run: |
          echo Nothing to see in the scirpt
          echo Here is what is in the folder
          ls -a
#           script: |
#             cd /home/project/build
#             pm2 delete app
#             chmod 777 -R /home/project/build/Github-Portfolio-Web-Service
#             rm -r /home/project/build/Github-Portfolio-Web-Service
#             git clone https://github.com/writingdeveloper/Github-Portfolio-Web-Service
#             cp .env Github-Portfolio-Web-Service/
#             cd Github-Portfolio-Web-Service
#             npm install
#             chmod 777 -R /home/project/build/Github-Portfolio-Web-Service
#             pm2 start app.js --watch
