name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: expressme.dev
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/project/build
            rm -r /home/project/build/Github-Portfolio-Web-Service
            git clone https://github.com/writingdeveloper/Github-Portfolio-Web-Service
            cp .env Github-Portfolio-Web-Service/
            cd Github-Portfolio-Web-Service # navigate into the repo
            npm install # install dependencies 
            npm start
