on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2

    - name: 📂 Sync files
      uses: writingdeveloper/Github-Portfolio-Web-Service
      with:
        server: ${{ secrets.FTPSURL }}
        username: ${{ secrets.FTPSUSERNAME }}
        password: ${{ secrets.FTPSPASSWORD }}
        dry-run: true
