name: Deploy application
 
on:
  push:
    branches: [ master ]
 
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy NodeJS app
        uses: appleboy/ssh-action@v0.1.2
        with:
          host: expressme.dev
          username: ubuntu
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/project/build
            cd ~/my-express-app/ # navigate into the folder
            git clone https://github.com/writingdeveloper/Github-Portfolio-Web-Service
            cd Github-Portfolio-Web-Service # navigate into the repo
            npm install # install dependencies 
            pm2 start app.js # start as a background service.
            console.log('Finish');
